# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//libamdf/build_tools/bazel:cc.bzl", "amdf_cc_library")

package(
    default_visibility = ["//libamdf/cts:__subpackages__"],
    licenses = ["notice"],
)

exports_files([
    "README.md",
    "generate.py",
    "lds_exchange.c",
    "lds_exchange_gfx942.json",
    "private_roundtrip.c",
    "private_roundtrip_gfx942.json",
    "transform.c",
    "transform_gfx942.json",
])

amdf_cc_library(
    name = "image",
    testonly = True,
    hdrs = ["image.h"],
)

amdf_cc_library(
    name = "transform_gfx942",
    testonly = True,
    hdrs = [
        "transform.h",
        "transform_gfx942.h",
    ],
    deps = [":image"],
)

amdf_cc_library(
    name = "lds_exchange_gfx942",
    testonly = True,
    hdrs = ["lds_exchange_gfx942.h"],
    deps = [":image"],
)

amdf_cc_library(
    name = "private_roundtrip_gfx942",
    testonly = True,
    hdrs = ["private_roundtrip_gfx942.h"],
    deps = [":image"],
)
