// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// Generated by generate.py; see transform_gfx1151.json.
// Compiler descriptor and code remain paired in this little-endian image.

#ifndef AMDF_CTS_GPU_KERNELS_TRANSFORM_GFX1151_H_
#define AMDF_CTS_GPU_KERNELS_TRANSFORM_GFX1151_H_

#include <array>
#include <cstdint>

#include "libamdf/cts/gpu/kernels/image.h"

namespace kernels::gfx1151_transform {

inline constexpr char kImageSha256[] =
    "9975f125e7b3db470584bfb52937bd51fcb226e7df505af2bde166043d7ceaba";
inline constexpr uint32_t kDescriptorByteOffset = 0;
inline constexpr uint32_t kEntryByteOffset = 256;
inline constexpr uint32_t kKernargByteLength = 24;
inline constexpr uint32_t kKernargAlignment = 16;
inline constexpr uint32_t kGroupSegmentByteLength = 0;
inline constexpr uint32_t kPrivateSegmentByteLength = 0;
inline constexpr uint16_t kWorkgroupSize = 64;
inline constexpr uint32_t kComputePgmRsrc1 = 0xe0af0000u;
inline constexpr uint32_t kComputePgmRsrc2 = 0x00000084u;
inline constexpr uint32_t kComputePgmRsrc3 = 0x00000020u;

alignas(256) inline constexpr std::array<uint32_t, 224> kImage = {
    0x00000000u, 0x00000000u, 0x00000018u, 0x00000000u, 0x00000100u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000020u, 0xe0af0000u, 0x00000084u, 0x00000408u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xf4040100u,
    0xf8000010u, 0xd6560000u, 0x04010c02u, 0xbe82007eu, 0xbf89fc07u,
    0xbf870001u, 0x7d980004u, 0xbfa50018u, 0xf4080000u, 0xf8000000u,
    0x7e020280u, 0xbf8700a1u, 0xd73c0000u, 0x02020082u, 0xbf89fc07u,
    0xd7006a02u, 0x02020000u, 0xbf870001u, 0xd5207c03u, 0x01aa0201u,
    0xbe800005u, 0xd7006a00u, 0x02020002u, 0xdc520000u, 0x027c0002u,
    0xd5207c01u, 0x01aa0203u, 0xbf8903f7u, 0xd6fe7c02u, 0x00010702u,
    0xdc6a0000u, 0x007c0200u, 0xbfb00000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
    0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u, 0xbf9f0000u,
};

inline constexpr Image kExecutable = {
    kImage.data(),
    sizeof(kImage),
    kDescriptorByteOffset,
    kImageSha256,
};

}  // namespace kernels::gfx1151_transform

#endif  // AMDF_CTS_GPU_KERNELS_TRANSFORM_GFX1151_H_
