# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//libamdf/build_tools/bazel:cc.bzl", "amdf_cc_library")

package(
    default_visibility = [
        "//libamdf/cts/interop/gpu/xdna:__subpackages__",
        "//libamdf/cts/xdna:__subpackages__",
    ],
    features = ["layering_check"],
    licenses = ["notice"],
)

exports_files([
    "README.md",
    "generate.py",
    "mul_i32.cc",
    "mul_i32.json",
])

amdf_cc_library(
    name = "mul_i32",
    testonly = True,
    hdrs = ["mul_i32.h"],
)
